#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/preinst.d && run-parts --arg="4.8.13-g2b627209-dirty" --arg="/boot/vmlinuz-4.8.13-g2b627209-dirty" /etc/kernel/preinst.d
exit 0
